kind: Kustomization
namespace: vgallery-prod
resources:
- namespace.yaml
- vault-static-secret.yaml
- migrate-job.yaml
- ../../../base/vgallery
images:
- name: lightstone1/vgallery-prod
  newName: lightstone1/vgallery-prod
  newTag: 01b833f6135e975838e1420625be20552def83f5
- name: lightstone1/vgallery-prod-migrate
  newName: lightstone1/vgallery-prod-migrate
  newTag: 01b833f6135e975838e1420625be20552def83f5
apiVersion: kustomize.config.k8s.io/v1beta1
