kind: Kustomization
namespace: vgallery-prod
resources:
- namespace.yaml
- vault-static-secret.yaml
- migrate-job.yaml
- ../../../base/vgallery
images:
- name: lightstone1/vgallery-prod
  newName: lightstone1/vgallery-prod
  newTag: 00da11096ec02b8e6800cb7b672c84a35099a2d9
- name: lightstone1/vgallery-prod-migrate
  newName: lightstone1/vgallery-prod-migrate
  newTag: 00da11096ec02b8e6800cb7b672c84a35099a2d9
apiVersion: kustomize.config.k8s.io/v1beta1
