kind: Kustomization
namespace: vgallery-prod
resources:
- namespace.yaml
- vault-static-secret.yaml
- migrate-job.yaml
- ../../../base/vgallery
images:
- name: lightstone1/vgallery-prod
  newName: lightstone1/vgallery-prod
  newTag: df92972605cd6898b463af86aa0f1da51a4eb3bc
- name: lightstone1/vgallery-prod-migrate
  newName: lightstone1/vgallery-prod-migrate
  newTag: df92972605cd6898b463af86aa0f1da51a4eb3bc
apiVersion: kustomize.config.k8s.io/v1beta1
