apiVersion: v1
kind: ServiceAccount
metadata:
  name: vgallery-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vgallery-vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: vault-secrets-operator-system/cagea1-vault
  kubernetes:
    role: config-vso
    serviceAccount: vgallery-vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vgallery-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  type: kv-v2
  mount: kv
  path: vgallery-prod-secret
  refreshAfter: 1h
  vaultAuthRef: vgallery-vault-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: vgallery-deployment
  destination:
    create: true
    overwrite: true
    name: vgallery-prod-secret
    transformation:
      excludeRaw: false
